### ISSUE TITLE
console无法运行

### ISSUE THREAD

**Issue by yxtwl94** [EVA-JianJun/AutoCython#1]
使用python -m AutoCython无法找到模块无法运行

No module named AutoCython.__main__; 'AutoCython' is a package and cannot be directly executed

**Comment by EVA-JianJun** [comment]
@yxtwl94  直接 `AutoCython` 就可以运行, 不用使用 `python -m`, 如果是 Windows 在你的 Python 安装文件夹下 Scripts 还可以找到 `AutoCython.exe`, 你试试
